/** Grade 12 names from the class list. Forename + surname. */
export const CLASS_NAMES: string[] = [
  "Minato ABE",
  "Ashita AGARWAL",
  "Astha AGARWAL",
  "Krishiv AGRAWAL",
  "Ziyu AI",
  "Roman AJAPNGU NJENDE",
  "Christ Mignon AKOUYA-A",
  "Joaquin Inigo ALCANTARA",
  "Kanha AM",
  "Nikita ANCHAN",
  "Nozomu Samuel ANDO",
  "Mina June ANDRAULT CRUBEZY",
  "Nikita ARANI",
  "Aki ARAYA",
  "Arnav ARORA",
  "Rohan ARUN",
  "Ruthu ARUN",
  "Anastasia BAKURIYA",
  "Clara BALDASSO MONTEIRO",
  "Camilla BECKER",
  "Shlok BEHURA",
  "Scotia BELLIVEAU",
  "Oceane BENNUR",
  "Mihika BHAN",
  "Gabriel BIJAOUI",
  "Amelie BROGDEN",
  "Jake BROGDEN",
  "Thea BUCHSBAUM",
  "Anna BURTON",
  "Miles BURTON",
  "Karl Rasmus BYSKOV",
  "Sofia CABEZON WANG",
  "Zhiming CAO",
  "Riley CARMICHAEL",
  "Francisco CHAN",
  "Misty CHAN",
  "Ishaan CHATURVEDI",
  "Salome CHAUFFAILLE",
  "Ho-Yun CHEN",
  "Jia Yin CHEN",
  "Zhiwei CHEN",
  "Xi CHENG",
  "Navya CHHAWCHHARIA",
  "Sailagnaa CHHOTRAY",
  "Hyunjoon CHO",
  "Harang CHOI",
  "Jina CHOI",
  "Ka Lok CHOI",
  "Shreya CHOWDHARY",
  "Yana CHOWDHURY",
  "Chih Wei CHU",
  "Heeyun CHUN",
  "Leone CIUTI",
  "Justine CONXICOEUR",
  "Harriet COURT",
  "Kurt CZERNY",
  "Roan Arjun DAGUR",
  "James DE OUDE",
  "Benicio DELGADO MONTERO",
  "Kexin DENG",
  "William DEWBERRY",
  "Alesia Samikai DIAZ DE LA VEGA GUERRERO",
  "Zoe Alejandra DIAZ PAYANO",
  "Onur DILER",
  "Nathan DING",
  "Zhixuan DING",
  "Kingyel Wangchuk DORJI",
  "Martin DUAN",
  "Inika DUMIR",
  "Allegra DUNHAM",
  "Nica EAPEN",
  "Ela EMIROGLU",
  "Mattijs FAVAITS",
  "Alexandre FISCHLER",
  "Conor FITZGERALD",
  "Kaitlyn FOO",
  "Ann-Marie FORSTER",
  "Lilliana FRANCE",
  "Emma FRANK",
  "Branson GAN",
  "Yishan GAO",
  "Agastya GARODIA",
  "Ue Chian GO",
  "Sara GOMEZ GARCIA",
  "Jiayue GONG",
  "Amalia GONZALEZ LOUREIRO",
  "Kiara GONZALEZ NAIR",
  "Thelma GORMAND",
  "Lachlan GRANT-PERRY",
  "Alexis GREEN",
  "Emmanuel GRYSEELS",
  "Seojoon HAHM",
  "Sam HAHN",
  "Antonia HALL",
  "Audrey HALLMARK",
  "Isabella HANSEN",
  "Mohammad Abrarul HAQUE",
  "Keira HAUSKE",
  "Isabella HAWKES",
  "Sijia HE",
  "Yuanzhuo HE",
  "Jack HEALY",
  "Chanelle HERHO",
  "Erinna HERMAN",
  "Gabriel HERNANDEZ SOLIS",
  "Analie HERPIN",
  "Rei HIROSE",
  "Mia Su Yan H'NG",
  "Floris HOLST",
  "Canran HU",
  "Jinyi HU",
  "Jiayi HUANG",
  "Yubo HUANG",
  "Yunzhe HUANG",
  "Chan HUH",
  "Louis HUYNH",
  "Gina HWANG",
  "Hojoon HWANG",
  "Jaejoon HWANG",
  "Sora ITO",
  "Ananiya JAIN",
  "Yoonjin JANG",
  "Yena JEE",
  "Ruyi JI",
  "Yinuo JIA",
  "Hengjie JIANG",
  "Yueqian JIANG",
  "Alina JIVRAJ",
  "Lara JOHANSEN",
  "Ami KADONO",
  "Raghav KALRA",
  "Sanjana KANAMARLAPUDI",
  "Jihyeon KANG",
  "Sahil KANKANI",
  "Kanav KARMAKAR",
  "Alyssa KAROONYAVANICH",
  "Tianyu KE",
  "Daniel KHAFI",
  "Simrin KHAITAN",
  "Zain KHAN",
  "Anvi KHANDELWAL",
  "Avi KHURANA",
  "Lukas KIESSELBACH",
  "Doyun KIM",
  "Hajoon KIM",
  "Kaon KIM",
  "Kyurin KIM",
  "Minyu KIM",
  "Suhyun KO",
  "Riko KOSATO",
  "Shota KUGAWA",
  "Viviënne KUIPERS",
  "Dylan KUPPUSAMY",
  "Mari KUTSUZAWA",
  "Minjun KWAK",
  "Minseo KWAK",
  "Joonwoo KWON",
  "Isaure LANGLOIS",
  "Jolita LAPSYS",
  "Eden LEE",
  "Gaeun LEE",
  "Jae Hyung LEE",
  "Keitaro LEE",
  "Yeon-Joo LEE",
  "Anders LESLIE",
  "Angeline LEVAR",
  "Mateo LEWIN-WEI",
  "Alexander LI",
  "Boshen LI",
  "Jiarong LI",
  "Yiran LI",
  "Yunduo LI",
  "Yuxuan LI",
  "Caini LIAN",
  "Louanne LINDENAU",
  "Myat Soe Linn LINN",
  "Junyan LIU",
  "Yi LIU",
  "Amy LLOYD",
  "Kut Cheung Ken LO",
  "Noe Tenggis LORINET",
  "Isabel LOWE",
  "Siming LU",
  "Jiashang LUAN",
  "Yilan LYU",
  "Ze LYU",
  "Dan MAGUID",
  "Aubrey MAK",
  "Maxime MALAPERT",
  "Laila MALONE",
  "Claire Aimee MAMADOU LIM",
  "Mio MANABE",
  "Mikaila MATHEW",
  "Suvansh MATHUR",
  "Jamie MCBRIDE",
  "Emma MCKENZIE",
  "Phetegue Abdoul Malick MEITE",
  "Linde MEULENDIJKS",
  "Ye Myat MHOU",
  "Ayala MICHAELY",
  "Lea MIET",
  "Oren MILBURN",
  "Juliette MILLER",
  "Lily MINFORD",
  "Olivia MONTAGUE",
  "Taisei MORI",
  "Rohan MUNDARGI",
  "Kotaro NAKAMURA",
  "Simelokuhle NKAMBULE",
  "Kudzaishe Sewereni NKHATA",
  "Marcus NORDSTROM",
  "Naw Ehka NORK",
  "Mareb OCHIENG",
  "Matthew Junghoon OH",
  "Deniz OKUR",
  "Yuvaan PANDEY",
  "Aveev PANKAJ",
  "Daeun PARK",
  "Joonggeun PARK",
  "Youbin PARK",
  "Luka PECANAC",
  "Cameron PEFIANCO",
  "Karolina PERDICES",
  "Lautaro Gabriel PEREZ MARTINEZ",
  "Sol Rey PERRYMAN",
  "Leo-Zhong PICKERING",
  "Asep PUTRA",
  "Chuhe QIAN",
  "Xinyue QIAN",
  "Yilin QIAN",
  "Veronica RANA",
  "Kyra RAWAT",
  "Haseet REKURAM",
  "Zefeng REN",
  "Olivier RHEAUME",
  "Olivia RITCH",
  "Grace ROBERTS",
  "Fiona RYAN",
  "Amrit SAHA",
  "Ashlesha SAHOO",
  "Sayaka SAKURAI",
  "Majken SALOKANGAS",
  "Anusha SALUJA",
  "Siddhant SAXENA",
  "Isabella SCHUELLER",
  "Victor SCHUMANN",
  "Mari SERIZAWA",
  "Zhiyuan SHI",
  "Jia-Rui SHIH",
  "Sonia SHOAIB",
  "Aamir SIDDIQUI",
  "Kavi SIDHU",
  "Lila SILBORN",
  "Jiaxing SONG",
  "Emmanuel SORO",
  "Thitirat SRINUALNAD",
  "Anya SRIVASTAVA",
  "Koken SUGITA",
  "Weicheng SUN",
  "Ruhani SURANA",
  "Kei TAKAHASHI",
  "Bun TAKEDA",
  "Gali TAL",
  "Finn TAN",
  "Ryan TAN",
  "Tiancheng TANG",
  "Nina TAYLOR",
  "Zac Michael TEOW",
  "Alex THOMAS",
  "Farrah TOWN",
  "Emmy TRANTER",
  "Khanh Ngan TRIEU",
  "Ava TSO",
  "Shoken TSURUMARU",
  "Joseph TU",
  "Lauren UNSWORTH",
  "Elaine VAN DER CHIJS",
  "Sophia VATCHKOVA",
  "Sofiia VENCHAK",
  "Estella VUJANOVIC",
  "Aashman WADHWA",
  "Bo-Jun (Harry) WANG",
  "Haobo Felix WANG",
  "Kevin WANG",
  "Leshan WANG",
  "Lihao WANG",
  "Peilin WANG",
  "Shuge WANG",
  "Weitian WANG",
  "Youxiang WANG",
  "Yunlei WANG",
  "Yuxuan WANG",
  "Jayden WANGSAWIDJAJA",
  "Ashwini WARAN",
  "Manya WASU",
  "Oliver WATERS",
  "Xin WEN",
  "Yun-Yun (Corrine) WEN",
  "Alex WILLS",
  "Nicholas WONDRA",
  "Yin Hoi Aiden WONG",
  "Yu Fan WU",
  "Yujie WU",
  "Zihan WU",
  "Jianye XU",
  "Jiaqi XU",
  "Tsz Nok XU",
  "Chanhong YAIM",
  "Saku YAMAUCHI",
  "Han YANG",
  "Runmeng YE",
  "Jiayu YING",
  "Mia YOKOKAWA",
  "Zoe ZAMAN",
  "Anastasia ZAPSA",
  "Zhai ZHAI",
  "Zixi ZHAN",
  "Aria ZHANG",
  "Diana Bai Han ZHANG",
  "Ethan ZHANG",
  "Jinghan ZHANG",
  "Shuwei ZHANG",
  "Xinchen ZHANG",
  "Yuchen Joy ZHANG",
  "Yuhan ZHANG",
  "Zerlina ZHANG",
  "Boran ZHAO",
  "Jingtong ZHEN",
  "Ruilin ZHENG",
  "Zihan ZHOU",
  "Amy ZHU",
  "Chengyu ZHU",
  "Cindy ZHU",
  "Haoyue ZHU",
  "Hongying ZHU",
  "Ty ZIEMER",
  "Lukas ZIETZ",
  "Lina ZINCHIK",
  "Zhiyong ZUO",
];
