-- Class of 2027 names that book at full price.
-- Complimentary tickets stay only on the 25 reserved recipients in 06_comp_recipients.sql.
-- Re-runnable: upserts on (official_name, family_name) and never overwrites a reserved recipient's comp_seats.

create unique index if not exists students_official_family_key
  on students (official_name, family_name);

insert into students (name, grade, comp_seats, preferred_name, official_name, family_name) values
  ('Minato ABE', '12', 0, 'Minato', 'Minato', 'ABE'),
  ('Ashita AGARWAL', '12', 0, 'Ashita', 'Ashita', 'AGARWAL'),
  ('Astha AGARWAL', '12', 0, 'Astha', 'Astha', 'AGARWAL'),
  ('Krishiv AGRAWAL', '12', 0, 'Krishiv', 'Krishiv', 'AGRAWAL'),
  ('Ziyu AI', '12', 0, 'Ziyu', 'Ziyu', 'AI'),
  ('Joaquin Inigo ALCANTARA', '12', 0, 'Joaquin Inigo', 'Joaquin Inigo', 'ALCANTARA'),
  ('Nikita ANCHAN', '12', 0, 'Nikita', 'Nikita', 'ANCHAN'),
  ('Nozomu Samuel ANDO', '12', 0, 'Nozomu Samuel', 'Nozomu Samuel', 'ANDO'),
  ('Nikita ARANI', '12', 0, 'Nikita', 'Nikita', 'ARANI'),
  ('Aki ARAYA', '12', 0, 'Aki', 'Aki', 'ARAYA'),
  ('Arnav ARORA', '12', 0, 'Arnav', 'Arnav', 'ARORA'),
  ('Rohan ARUN', '12', 0, 'Rohan', 'Rohan', 'ARUN'),
  ('Ruthu ARUN', '12', 0, 'Ruthu', 'Ruthu', 'ARUN'),
  ('Clara BALDASSO MONTEIRO', '12', 0, 'Clara', 'Clara', 'BALDASSO MONTEIRO'),
  ('Camilla BECKER', '12', 0, 'Camilla', 'Camilla', 'BECKER'),
  ('Shlok BEHURA', '12', 0, 'Shlok', 'Shlok', 'BEHURA'),
  ('Scotia BELLIVEAU', '12', 0, 'Scotia', 'Scotia', 'BELLIVEAU'),
  ('Oceane BENNUR', '12', 0, 'Oceane', 'Oceane', 'BENNUR'),
  ('Mihika BHAN', '12', 0, 'Mihika', 'Mihika', 'BHAN'),
  ('Gabriel BIJAOUI', '12', 0, 'Gabriel', 'Gabriel', 'BIJAOUI'),
  ('Amelie BROGDEN', '12', 0, 'Amelie', 'Amelie', 'BROGDEN'),
  ('Jake BROGDEN', '12', 0, 'Jake', 'Jake', 'BROGDEN'),
  ('Thea BUCHSBAUM', '12', 0, 'Thea', 'Thea', 'BUCHSBAUM'),
  ('Anna BURTON', '12', 0, 'Anna', 'Anna', 'BURTON'),
  ('Miles BURTON', '12', 0, 'Miles', 'Miles', 'BURTON'),
  ('Karl Rasmus BYSKOV', '12', 0, 'Karl Rasmus', 'Karl Rasmus', 'BYSKOV'),
  ('Sofia CABEZON WANG', '12', 0, 'Sofia', 'Sofia', 'CABEZON WANG'),
  ('Zhiming CAO', '12', 0, 'Zhiming', 'Zhiming', 'CAO'),
  ('Riley CARMICHAEL', '12', 0, 'Riley', 'Riley', 'CARMICHAEL'),
  ('Francisco CHAN', '12', 0, 'Francisco', 'Francisco', 'CHAN'),
  ('Misty CHAN', '12', 0, 'Misty', 'Misty', 'CHAN'),
  ('Ishaan CHATURVEDI', '12', 0, 'Ishaan', 'Ishaan', 'CHATURVEDI'),
  ('Salome CHAUFFAILLE', '12', 0, 'Salome', 'Salome', 'CHAUFFAILLE'),
  ('Ho-Yun CHEN', '12', 0, 'Ho-Yun', 'Ho-Yun', 'CHEN'),
  ('Jia Yin CHEN', '12', 0, 'Jia Yin', 'Jia Yin', 'CHEN'),
  ('Zhiwei CHEN', '12', 0, 'Zhiwei', 'Zhiwei', 'CHEN'),
  ('Xi CHENG', '12', 0, 'Xi', 'Xi', 'CHENG'),
  ('Navya CHHAWCHHARIA', '12', 0, 'Navya', 'Navya', 'CHHAWCHHARIA'),
  ('Sailagnaa CHHOTRAY', '12', 0, 'Sailagnaa', 'Sailagnaa', 'CHHOTRAY'),
  ('Hyunjoon CHO', '12', 0, 'Hyunjoon', 'Hyunjoon', 'CHO'),
  ('Harang CHOI', '12', 0, 'Harang', 'Harang', 'CHOI'),
  ('Jina CHOI', '12', 0, 'Jina', 'Jina', 'CHOI'),
  ('Ka Lok CHOI', '12', 0, 'Ka Lok', 'Ka Lok', 'CHOI'),
  ('Shreya CHOWDHARY', '12', 0, 'Shreya', 'Shreya', 'CHOWDHARY'),
  ('Yana CHOWDHURY', '12', 0, 'Yana', 'Yana', 'CHOWDHURY'),
  ('Chih Wei CHU', '12', 0, 'Chih Wei', 'Chih Wei', 'CHU'),
  ('Heeyun CHUN', '12', 0, 'Heeyun', 'Heeyun', 'CHUN'),
  ('Leone CIUTI', '12', 0, 'Leone', 'Leone', 'CIUTI'),
  ('Justine CONXICOEUR', '12', 0, 'Justine', 'Justine', 'CONXICOEUR'),
  ('Harriet COURT', '12', 0, 'Harriet', 'Harriet', 'COURT'),
  ('Kurt CZERNY', '12', 0, 'Kurt', 'Kurt', 'CZERNY'),
  ('Roan Arjun DAGUR', '12', 0, 'Roan Arjun', 'Roan Arjun', 'DAGUR'),
  ('James DE OUDE', '12', 0, 'James', 'James', 'DE OUDE'),
  ('Kexin DENG', '12', 0, 'Kexin', 'Kexin', 'DENG'),
  ('William DEWBERRY', '12', 0, 'William', 'William', 'DEWBERRY'),
  ('Onur DILER', '12', 0, 'Onur', 'Onur', 'DILER'),
  ('Nathan DING', '12', 0, 'Nathan', 'Nathan', 'DING'),
  ('Zhixuan DING', '12', 0, 'Zhixuan', 'Zhixuan', 'DING'),
  ('Martin DUAN', '12', 0, 'Martin', 'Martin', 'DUAN'),
  ('Inika DUMIR', '12', 0, 'Inika', 'Inika', 'DUMIR'),
  ('Allegra DUNHAM', '12', 0, 'Allegra', 'Allegra', 'DUNHAM'),
  ('Nica EAPEN', '12', 0, 'Nica', 'Nica', 'EAPEN'),
  ('Ela EMIROGLU', '12', 0, 'Ela', 'Ela', 'EMIROGLU'),
  ('Mattijs FAVAITS', '12', 0, 'Mattijs', 'Mattijs', 'FAVAITS'),
  ('Alexandre FISCHLER', '12', 0, 'Alexandre', 'Alexandre', 'FISCHLER'),
  ('Conor FITZGERALD', '12', 0, 'Conor', 'Conor', 'FITZGERALD'),
  ('Kaitlyn FOO', '12', 0, 'Kaitlyn', 'Kaitlyn', 'FOO'),
  ('Ann-Marie FORSTER', '12', 0, 'Ann-Marie', 'Ann-Marie', 'FORSTER'),
  ('Lilliana FRANCE', '12', 0, 'Lilliana', 'Lilliana', 'FRANCE'),
  ('Emma FRANK', '12', 0, 'Emma', 'Emma', 'FRANK'),
  ('Branson GAN', '12', 0, 'Branson', 'Branson', 'GAN'),
  ('Yishan GAO', '12', 0, 'Yishan', 'Yishan', 'GAO'),
  ('Agastya GARODIA', '12', 0, 'Agastya', 'Agastya', 'GARODIA'),
  ('Ue Chian GO', '12', 0, 'Ue Chian', 'Ue Chian', 'GO'),
  ('Jiayue GONG', '12', 0, 'Jiayue', 'Jiayue', 'GONG'),
  ('Amalia GONZALEZ LOUREIRO', '12', 0, 'Amalia', 'Amalia', 'GONZALEZ LOUREIRO'),
  ('Kiara GONZALEZ NAIR', '12', 0, 'Kiara', 'Kiara', 'GONZALEZ NAIR'),
  ('Thelma GORMAND', '12', 0, 'Thelma', 'Thelma', 'GORMAND'),
  ('Lachlan GRANT-PERRY', '12', 0, 'Lachlan', 'Lachlan', 'GRANT-PERRY'),
  ('Alexis GREEN', '12', 0, 'Alexis', 'Alexis', 'GREEN'),
  ('Emmanuel GRYSEELS', '12', 0, 'Emmanuel', 'Emmanuel', 'GRYSEELS'),
  ('Seojoon HAHM', '12', 0, 'Seojoon', 'Seojoon', 'HAHM'),
  ('Sam HAHN', '12', 0, 'Sam', 'Sam', 'HAHN'),
  ('Antonia HALL', '12', 0, 'Antonia', 'Antonia', 'HALL'),
  ('Audrey HALLMARK', '12', 0, 'Audrey', 'Audrey', 'HALLMARK'),
  ('Isabella HANSEN', '12', 0, 'Isabella', 'Isabella', 'HANSEN'),
  ('Mohammad Abrarul HAQUE', '12', 0, 'Mohammad Abrarul', 'Mohammad Abrarul', 'HAQUE'),
  ('Keira HAUSKE', '12', 0, 'Keira', 'Keira', 'HAUSKE'),
  ('Isabella HAWKES', '12', 0, 'Isabella', 'Isabella', 'HAWKES'),
  ('Sijia HE', '12', 0, 'Sijia', 'Sijia', 'HE'),
  ('Yuanzhuo HE', '12', 0, 'Yuanzhuo', 'Yuanzhuo', 'HE'),
  ('Jack HEALY', '12', 0, 'Jack', 'Jack', 'HEALY'),
  ('Chanelle HERHO', '12', 0, 'Chanelle', 'Chanelle', 'HERHO'),
  ('Erinna HERMAN', '12', 0, 'Erinna', 'Erinna', 'HERMAN'),
  ('Analie HERPIN', '12', 0, 'Analie', 'Analie', 'HERPIN'),
  ('Rei HIROSE', '12', 0, 'Rei', 'Rei', 'HIROSE'),
  ('Mia Su Yan H''NG', '12', 0, 'Mia Su Yan', 'Mia Su Yan', 'H''NG'),
  ('Floris HOLST', '12', 0, 'Floris', 'Floris', 'HOLST'),
  ('Canran HU', '12', 0, 'Canran', 'Canran', 'HU'),
  ('Jinyi HU', '12', 0, 'Jinyi', 'Jinyi', 'HU'),
  ('Jiayi HUANG', '12', 0, 'Jiayi', 'Jiayi', 'HUANG'),
  ('Yubo HUANG', '12', 0, 'Yubo', 'Yubo', 'HUANG'),
  ('Yunzhe HUANG', '12', 0, 'Yunzhe', 'Yunzhe', 'HUANG'),
  ('Chan HUH', '12', 0, 'Chan', 'Chan', 'HUH'),
  ('Louis HUYNH', '12', 0, 'Louis', 'Louis', 'HUYNH'),
  ('Gina HWANG', '12', 0, 'Gina', 'Gina', 'HWANG'),
  ('Hojoon HWANG', '12', 0, 'Hojoon', 'Hojoon', 'HWANG'),
  ('Jaejoon HWANG', '12', 0, 'Jaejoon', 'Jaejoon', 'HWANG'),
  ('Sora ITO', '12', 0, 'Sora', 'Sora', 'ITO'),
  ('Ananiya JAIN', '12', 0, 'Ananiya', 'Ananiya', 'JAIN'),
  ('Yoonjin JANG', '12', 0, 'Yoonjin', 'Yoonjin', 'JANG'),
  ('Yena JEE', '12', 0, 'Yena', 'Yena', 'JEE'),
  ('Ruyi JI', '12', 0, 'Ruyi', 'Ruyi', 'JI'),
  ('Yinuo JIA', '12', 0, 'Yinuo', 'Yinuo', 'JIA'),
  ('Hengjie JIANG', '12', 0, 'Hengjie', 'Hengjie', 'JIANG'),
  ('Yueqian JIANG', '12', 0, 'Yueqian', 'Yueqian', 'JIANG'),
  ('Alina JIVRAJ', '12', 0, 'Alina', 'Alina', 'JIVRAJ'),
  ('Lara JOHANSEN', '12', 0, 'Lara', 'Lara', 'JOHANSEN'),
  ('Ami KADONO', '12', 0, 'Ami', 'Ami', 'KADONO'),
  ('Raghav KALRA', '12', 0, 'Raghav', 'Raghav', 'KALRA'),
  ('Sanjana KANAMARLAPUDI', '12', 0, 'Sanjana', 'Sanjana', 'KANAMARLAPUDI'),
  ('Jihyeon KANG', '12', 0, 'Jihyeon', 'Jihyeon', 'KANG'),
  ('Sahil KANKANI', '12', 0, 'Sahil', 'Sahil', 'KANKANI'),
  ('Kanav KARMAKAR', '12', 0, 'Kanav', 'Kanav', 'KARMAKAR'),
  ('Alyssa KAROONYAVANICH', '12', 0, 'Alyssa', 'Alyssa', 'KAROONYAVANICH'),
  ('Tianyu KE', '12', 0, 'Tianyu', 'Tianyu', 'KE'),
  ('Daniel KHAFI', '12', 0, 'Daniel', 'Daniel', 'KHAFI'),
  ('Simrin KHAITAN', '12', 0, 'Simrin', 'Simrin', 'KHAITAN'),
  ('Zain KHAN', '12', 0, 'Zain', 'Zain', 'KHAN'),
  ('Anvi KHANDELWAL', '12', 0, 'Anvi', 'Anvi', 'KHANDELWAL'),
  ('Avi KHURANA', '12', 0, 'Avi', 'Avi', 'KHURANA'),
  ('Lukas KIESSELBACH', '12', 0, 'Lukas', 'Lukas', 'KIESSELBACH'),
  ('Doyun KIM', '12', 0, 'Doyun', 'Doyun', 'KIM'),
  ('Hajoon KIM', '12', 0, 'Hajoon', 'Hajoon', 'KIM'),
  ('Kaon KIM', '12', 0, 'Kaon', 'Kaon', 'KIM'),
  ('Kyurin KIM', '12', 0, 'Kyurin', 'Kyurin', 'KIM'),
  ('Minyu KIM', '12', 0, 'Minyu', 'Minyu', 'KIM'),
  ('Suhyun KO', '12', 0, 'Suhyun', 'Suhyun', 'KO'),
  ('Riko KOSATO', '12', 0, 'Riko', 'Riko', 'KOSATO'),
  ('Shota KUGAWA', '12', 0, 'Shota', 'Shota', 'KUGAWA'),
  ('Viviënne KUIPERS', '12', 0, 'Viviënne', 'Viviënne', 'KUIPERS'),
  ('Dylan KUPPUSAMY', '12', 0, 'Dylan', 'Dylan', 'KUPPUSAMY'),
  ('Mari KUTSUZAWA', '12', 0, 'Mari', 'Mari', 'KUTSUZAWA'),
  ('Minjun KWAK', '12', 0, 'Minjun', 'Minjun', 'KWAK'),
  ('Minseo KWAK', '12', 0, 'Minseo', 'Minseo', 'KWAK'),
  ('Joonwoo KWON', '12', 0, 'Joonwoo', 'Joonwoo', 'KWON'),
  ('Isaure LANGLOIS', '12', 0, 'Isaure', 'Isaure', 'LANGLOIS'),
  ('Jolita LAPSYS', '12', 0, 'Jolita', 'Jolita', 'LAPSYS'),
  ('Eden LEE', '12', 0, 'Eden', 'Eden', 'LEE'),
  ('Gaeun LEE', '12', 0, 'Gaeun', 'Gaeun', 'LEE'),
  ('Jae Hyung LEE', '12', 0, 'Jae Hyung', 'Jae Hyung', 'LEE'),
  ('Keitaro LEE', '12', 0, 'Keitaro', 'Keitaro', 'LEE'),
  ('Yeon-Joo LEE', '12', 0, 'Yeon-Joo', 'Yeon-Joo', 'LEE'),
  ('Anders LESLIE', '12', 0, 'Anders', 'Anders', 'LESLIE'),
  ('Angeline LEVAR', '12', 0, 'Angeline', 'Angeline', 'LEVAR'),
  ('Mateo LEWIN-WEI', '12', 0, 'Mateo', 'Mateo', 'LEWIN-WEI'),
  ('Boshen LI', '12', 0, 'Boshen', 'Boshen', 'LI'),
  ('Jiarong LI', '12', 0, 'Jiarong', 'Jiarong', 'LI'),
  ('Yiran LI', '12', 0, 'Yiran', 'Yiran', 'LI'),
  ('Yunduo LI', '12', 0, 'Yunduo', 'Yunduo', 'LI'),
  ('Yuxuan LI', '12', 0, 'Yuxuan', 'Yuxuan', 'LI'),
  ('Caini LIAN', '12', 0, 'Caini', 'Caini', 'LIAN'),
  ('Louanne LINDENAU', '12', 0, 'Louanne', 'Louanne', 'LINDENAU'),
  ('Myat Soe Linn LINN', '12', 0, 'Myat Soe Linn', 'Myat Soe Linn', 'LINN'),
  ('Junyan LIU', '12', 0, 'Junyan', 'Junyan', 'LIU'),
  ('Yi LIU', '12', 0, 'Yi', 'Yi', 'LIU'),
  ('Amy LLOYD', '12', 0, 'Amy', 'Amy', 'LLOYD'),
  ('Kut Cheung Ken LO', '12', 0, 'Kut Cheung Ken', 'Kut Cheung Ken', 'LO'),
  ('Noe Tenggis LORINET', '12', 0, 'Noe Tenggis', 'Noe Tenggis', 'LORINET'),
  ('Isabel LOWE', '12', 0, 'Isabel', 'Isabel', 'LOWE'),
  ('Siming LU', '12', 0, 'Siming', 'Siming', 'LU'),
  ('Jiashang LUAN', '12', 0, 'Jiashang', 'Jiashang', 'LUAN'),
  ('Yilan LYU', '12', 0, 'Yilan', 'Yilan', 'LYU'),
  ('Ze LYU', '12', 0, 'Ze', 'Ze', 'LYU'),
  ('Dan MAGUID', '12', 0, 'Dan', 'Dan', 'MAGUID'),
  ('Aubrey MAK', '12', 0, 'Aubrey', 'Aubrey', 'MAK'),
  ('Maxime MALAPERT', '12', 0, 'Maxime', 'Maxime', 'MALAPERT'),
  ('Laila MALONE', '12', 0, 'Laila', 'Laila', 'MALONE'),
  ('Claire Aimee MAMADOU LIM', '12', 0, 'Claire Aimee', 'Claire Aimee', 'MAMADOU LIM'),
  ('Mio MANABE', '12', 0, 'Mio', 'Mio', 'MANABE'),
  ('Mikaila MATHEW', '12', 0, 'Mikaila', 'Mikaila', 'MATHEW'),
  ('Suvansh MATHUR', '12', 0, 'Suvansh', 'Suvansh', 'MATHUR'),
  ('Jamie MCBRIDE', '12', 0, 'Jamie', 'Jamie', 'MCBRIDE'),
  ('Emma MCKENZIE', '12', 0, 'Emma', 'Emma', 'MCKENZIE'),
  ('Linde MEULENDIJKS', '12', 0, 'Linde', 'Linde', 'MEULENDIJKS'),
  ('Ye Myat MHOU', '12', 0, 'Ye Myat', 'Ye Myat', 'MHOU'),
  ('Ayala MICHAELY', '12', 0, 'Ayala', 'Ayala', 'MICHAELY'),
  ('Lea MIET', '12', 0, 'Lea', 'Lea', 'MIET'),
  ('Oren MILBURN', '12', 0, 'Oren', 'Oren', 'MILBURN'),
  ('Juliette MILLER', '12', 0, 'Juliette', 'Juliette', 'MILLER'),
  ('Lily MINFORD', '12', 0, 'Lily', 'Lily', 'MINFORD'),
  ('Olivia MONTAGUE', '12', 0, 'Olivia', 'Olivia', 'MONTAGUE'),
  ('Taisei MORI', '12', 0, 'Taisei', 'Taisei', 'MORI'),
  ('Rohan MUNDARGI', '12', 0, 'Rohan', 'Rohan', 'MUNDARGI'),
  ('Kotaro NAKAMURA', '12', 0, 'Kotaro', 'Kotaro', 'NAKAMURA'),
  ('Marcus NORDSTROM', '12', 0, 'Marcus', 'Marcus', 'NORDSTROM'),
  ('Matthew Junghoon OH', '12', 0, 'Matthew Junghoon', 'Matthew Junghoon', 'OH'),
  ('Deniz OKUR', '12', 0, 'Deniz', 'Deniz', 'OKUR'),
  ('Yuvaan PANDEY', '12', 0, 'Yuvaan', 'Yuvaan', 'PANDEY'),
  ('Aveev PANKAJ', '12', 0, 'Aveev', 'Aveev', 'PANKAJ'),
  ('Daeun PARK', '12', 0, 'Daeun', 'Daeun', 'PARK'),
  ('Joonggeun PARK', '12', 0, 'Joonggeun', 'Joonggeun', 'PARK'),
  ('Youbin PARK', '12', 0, 'Youbin', 'Youbin', 'PARK'),
  ('Cameron PEFIANCO', '12', 0, 'Cameron', 'Cameron', 'PEFIANCO'),
  ('Karolina PERDICES', '12', 0, 'Karolina', 'Karolina', 'PERDICES'),
  ('Sol Rey PERRYMAN', '12', 0, 'Sol Rey', 'Sol Rey', 'PERRYMAN'),
  ('Leo-Zhong PICKERING', '12', 0, 'Leo-Zhong', 'Leo-Zhong', 'PICKERING'),
  ('Chuhe QIAN', '12', 0, 'Chuhe', 'Chuhe', 'QIAN'),
  ('Xinyue QIAN', '12', 0, 'Xinyue', 'Xinyue', 'QIAN'),
  ('Yilin QIAN', '12', 0, 'Yilin', 'Yilin', 'QIAN'),
  ('Veronica RANA', '12', 0, 'Veronica', 'Veronica', 'RANA'),
  ('Kyra RAWAT', '12', 0, 'Kyra', 'Kyra', 'RAWAT'),
  ('Haseet REKURAM', '12', 0, 'Haseet', 'Haseet', 'REKURAM'),
  ('Zefeng REN', '12', 0, 'Zefeng', 'Zefeng', 'REN'),
  ('Olivier RHEAUME', '12', 0, 'Olivier', 'Olivier', 'RHEAUME'),
  ('Olivia RITCH', '12', 0, 'Olivia', 'Olivia', 'RITCH'),
  ('Grace ROBERTS', '12', 0, 'Grace', 'Grace', 'ROBERTS'),
  ('Fiona RYAN', '12', 0, 'Fiona', 'Fiona', 'RYAN'),
  ('Amrit SAHA', '12', 0, 'Amrit', 'Amrit', 'SAHA'),
  ('Ashlesha SAHOO', '12', 0, 'Ashlesha', 'Ashlesha', 'SAHOO'),
  ('Sayaka SAKURAI', '12', 0, 'Sayaka', 'Sayaka', 'SAKURAI'),
  ('Majken SALOKANGAS', '12', 0, 'Majken', 'Majken', 'SALOKANGAS'),
  ('Anusha SALUJA', '12', 0, 'Anusha', 'Anusha', 'SALUJA'),
  ('Siddhant SAXENA', '12', 0, 'Siddhant', 'Siddhant', 'SAXENA'),
  ('Isabella SCHUELLER', '12', 0, 'Isabella', 'Isabella', 'SCHUELLER'),
  ('Victor SCHUMANN', '12', 0, 'Victor', 'Victor', 'SCHUMANN'),
  ('Mari SERIZAWA', '12', 0, 'Mari', 'Mari', 'SERIZAWA'),
  ('Zhiyuan SHI', '12', 0, 'Zhiyuan', 'Zhiyuan', 'SHI'),
  ('Jia-Rui SHIH', '12', 0, 'Jia-Rui', 'Jia-Rui', 'SHIH'),
  ('Sonia SHOAIB', '12', 0, 'Sonia', 'Sonia', 'SHOAIB'),
  ('Aamir SIDDIQUI', '12', 0, 'Aamir', 'Aamir', 'SIDDIQUI'),
  ('Kavi SIDHU', '12', 0, 'Kavi', 'Kavi', 'SIDHU'),
  ('Lila SILBORN', '12', 0, 'Lila', 'Lila', 'SILBORN'),
  ('Jiaxing SONG', '12', 0, 'Jiaxing', 'Jiaxing', 'SONG'),
  ('Thitirat SRINUALNAD', '12', 0, 'Thitirat', 'Thitirat', 'SRINUALNAD'),
  ('Anya SRIVASTAVA', '12', 0, 'Anya', 'Anya', 'SRIVASTAVA'),
  ('Koken SUGITA', '12', 0, 'Koken', 'Koken', 'SUGITA'),
  ('Weicheng SUN', '12', 0, 'Weicheng', 'Weicheng', 'SUN'),
  ('Ruhani SURANA', '12', 0, 'Ruhani', 'Ruhani', 'SURANA'),
  ('Kei TAKAHASHI', '12', 0, 'Kei', 'Kei', 'TAKAHASHI'),
  ('Bun TAKEDA', '12', 0, 'Bun', 'Bun', 'TAKEDA'),
  ('Gali TAL', '12', 0, 'Gali', 'Gali', 'TAL'),
  ('Finn TAN', '12', 0, 'Finn', 'Finn', 'TAN'),
  ('Ryan TAN', '12', 0, 'Ryan', 'Ryan', 'TAN'),
  ('Tiancheng TANG', '12', 0, 'Tiancheng', 'Tiancheng', 'TANG'),
  ('Nina TAYLOR', '12', 0, 'Nina', 'Nina', 'TAYLOR'),
  ('Zac Michael TEOW', '12', 0, 'Zac Michael', 'Zac Michael', 'TEOW'),
  ('Alex THOMAS', '12', 0, 'Alex', 'Alex', 'THOMAS'),
  ('Farrah TOWN', '12', 0, 'Farrah', 'Farrah', 'TOWN'),
  ('Emmy TRANTER', '12', 0, 'Emmy', 'Emmy', 'TRANTER'),
  ('Ava TSO', '12', 0, 'Ava', 'Ava', 'TSO'),
  ('Shoken TSURUMARU', '12', 0, 'Shoken', 'Shoken', 'TSURUMARU'),
  ('Joseph TU', '12', 0, 'Joseph', 'Joseph', 'TU'),
  ('Lauren UNSWORTH', '12', 0, 'Lauren', 'Lauren', 'UNSWORTH'),
  ('Elaine VAN DER CHIJS', '12', 0, 'Elaine', 'Elaine', 'VAN DER CHIJS'),
  ('Sophia VATCHKOVA', '12', 0, 'Sophia', 'Sophia', 'VATCHKOVA'),
  ('Estella VUJANOVIC', '12', 0, 'Estella', 'Estella', 'VUJANOVIC'),
  ('Aashman WADHWA', '12', 0, 'Aashman', 'Aashman', 'WADHWA'),
  ('Bo-Jun (Harry) WANG', '12', 0, 'Bo-Jun (Harry)', 'Bo-Jun (Harry)', 'WANG'),
  ('Haobo Felix WANG', '12', 0, 'Haobo Felix', 'Haobo Felix', 'WANG'),
  ('Kevin WANG', '12', 0, 'Kevin', 'Kevin', 'WANG'),
  ('Leshan WANG', '12', 0, 'Leshan', 'Leshan', 'WANG'),
  ('Lihao WANG', '12', 0, 'Lihao', 'Lihao', 'WANG'),
  ('Peilin WANG', '12', 0, 'Peilin', 'Peilin', 'WANG'),
  ('Shuge WANG', '12', 0, 'Shuge', 'Shuge', 'WANG'),
  ('Weitian WANG', '12', 0, 'Weitian', 'Weitian', 'WANG'),
  ('Youxiang WANG', '12', 0, 'Youxiang', 'Youxiang', 'WANG'),
  ('Yunlei WANG', '12', 0, 'Yunlei', 'Yunlei', 'WANG'),
  ('Yuxuan WANG', '12', 0, 'Yuxuan', 'Yuxuan', 'WANG'),
  ('Jayden WANGSAWIDJAJA', '12', 0, 'Jayden', 'Jayden', 'WANGSAWIDJAJA'),
  ('Ashwini WARAN', '12', 0, 'Ashwini', 'Ashwini', 'WARAN'),
  ('Manya WASU', '12', 0, 'Manya', 'Manya', 'WASU'),
  ('Oliver WATERS', '12', 0, 'Oliver', 'Oliver', 'WATERS'),
  ('Xin WEN', '12', 0, 'Xin', 'Xin', 'WEN'),
  ('Yun-Yun (Corrine) WEN', '12', 0, 'Yun-Yun (Corrine)', 'Yun-Yun (Corrine)', 'WEN'),
  ('Alex WILLS', '12', 0, 'Alex', 'Alex', 'WILLS'),
  ('Nicholas WONDRA', '12', 0, 'Nicholas', 'Nicholas', 'WONDRA'),
  ('Yin Hoi Aiden WONG', '12', 0, 'Yin Hoi Aiden', 'Yin Hoi Aiden', 'WONG'),
  ('Yu Fan WU', '12', 0, 'Yu Fan', 'Yu Fan', 'WU'),
  ('Yujie WU', '12', 0, 'Yujie', 'Yujie', 'WU'),
  ('Zihan WU', '12', 0, 'Zihan', 'Zihan', 'WU'),
  ('Jianye XU', '12', 0, 'Jianye', 'Jianye', 'XU'),
  ('Jiaqi XU', '12', 0, 'Jiaqi', 'Jiaqi', 'XU'),
  ('Tsz Nok XU', '12', 0, 'Tsz Nok', 'Tsz Nok', 'XU'),
  ('Saku YAMAUCHI', '12', 0, 'Saku', 'Saku', 'YAMAUCHI'),
  ('Han YANG', '12', 0, 'Han', 'Han', 'YANG'),
  ('Runmeng YE', '12', 0, 'Runmeng', 'Runmeng', 'YE'),
  ('Jiayu YING', '12', 0, 'Jiayu', 'Jiayu', 'YING'),
  ('Mia YOKOKAWA', '12', 0, 'Mia', 'Mia', 'YOKOKAWA'),
  ('Zoe ZAMAN', '12', 0, 'Zoe', 'Zoe', 'ZAMAN'),
  ('Zhai ZHAI', '12', 0, 'Zhai', 'Zhai', 'ZHAI'),
  ('Zixi ZHAN', '12', 0, 'Zixi', 'Zixi', 'ZHAN'),
  ('Aria ZHANG', '12', 0, 'Aria', 'Aria', 'ZHANG'),
  ('Diana Bai Han ZHANG', '12', 0, 'Diana Bai Han', 'Diana Bai Han', 'ZHANG'),
  ('Ethan ZHANG', '12', 0, 'Ethan', 'Ethan', 'ZHANG'),
  ('Jinghan ZHANG', '12', 0, 'Jinghan', 'Jinghan', 'ZHANG'),
  ('Shuwei ZHANG', '12', 0, 'Shuwei', 'Shuwei', 'ZHANG'),
  ('Xinchen ZHANG', '12', 0, 'Xinchen', 'Xinchen', 'ZHANG'),
  ('Yuchen Joy ZHANG', '12', 0, 'Yuchen Joy', 'Yuchen Joy', 'ZHANG'),
  ('Yuhan ZHANG', '12', 0, 'Yuhan', 'Yuhan', 'ZHANG'),
  ('Zerlina ZHANG', '12', 0, 'Zerlina', 'Zerlina', 'ZHANG'),
  ('Boran ZHAO', '12', 0, 'Boran', 'Boran', 'ZHAO'),
  ('Jingtong ZHEN', '12', 0, 'Jingtong', 'Jingtong', 'ZHEN'),
  ('Ruilin ZHENG', '12', 0, 'Ruilin', 'Ruilin', 'ZHENG'),
  ('Zihan ZHOU', '12', 0, 'Zihan', 'Zihan', 'ZHOU'),
  ('Amy ZHU', '12', 0, 'Amy', 'Amy', 'ZHU'),
  ('Chengyu ZHU', '12', 0, 'Chengyu', 'Chengyu', 'ZHU'),
  ('Cindy ZHU', '12', 0, 'Cindy', 'Cindy', 'ZHU'),
  ('Haoyue ZHU', '12', 0, 'Haoyue', 'Haoyue', 'ZHU'),
  ('Hongying ZHU', '12', 0, 'Hongying', 'Hongying', 'ZHU'),
  ('Ty ZIEMER', '12', 0, 'Ty', 'Ty', 'ZIEMER'),
  ('Lukas ZIETZ', '12', 0, 'Lukas', 'Lukas', 'ZIETZ'),
  ('Lina ZINCHIK', '12', 0, 'Lina', 'Lina', 'ZINCHIK'),
  ('Zhiyong ZUO', '12', 0, 'Zhiyong', 'Zhiyong', 'ZUO')
on conflict (official_name, family_name) do update set
  name = excluded.name,
  grade = excluded.grade,
  preferred_name = excluded.preferred_name,
  official_name = excluded.official_name,
  family_name = excluded.family_name,
  comp_seats = students.comp_seats;

-- Sample rows have no family_name. They never receive complimentary tickets.
update students
set comp_seats = 0
where family_name is null;

